name: todo_server_dartling_mysql
version: 0.0.1
author: Dzenan Ridjanovic <dzenanr@gmail.com>
description: To learn how to use MySQL and client-server communication.
homepage: http://ondart.me/
dependencies:
  dartling:
    git: git://github.com/dzenanr/dartling.git
  sqljocky: any
