name: todo_client_idb
version: 2.0.1
author: Dzenan Ridjanovic <dzenanr@gmail.com>
description: To learn how to use IndexedDB and client-server communication.
homepage: http://ondart.me/
dependencies:
  browser: any
